name: pqc_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - liboqs>=0.9.0      # Esto instala la librerÃ­a C compilada (Binarios)
  - cryptography>=41.0.0
  - streamlit>=1.28.0
  - pandas>=2.0.0
  - pip
  - pip:
    # Esto instala el wrapper de Python directamente desde su repo oficial
    - liboqs-python @ git+https://github.com/open-quantum-safe/liboqs-python.git